import { expect, test } from '@playwright/test'

test('desktop core life loop and settings', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'desktop-only flow')
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await expect(page).toHaveTitle('AI Life Worlds · 人生世界')
  await expect(page.getByRole('main').getByRole('heading', { name: '晨雾镇' })).toBeVisible()
  const before = await page.locator('.action-card').allTextContents()
  await page.locator('.action-card').first().click()
  await expect(page.locator('.action-feedback')).toBeVisible()
  const after = await page.locator('.action-card').allTextContents()
  expect(new Set(after).size).toBe(after.length)
  expect(after).not.toEqual(before)
  await page.locator('.nav-item').filter({ hasText: '角色' }).click()
  await page.getByRole('button', { name: '编辑档案' }).click()
  await expect(page.getByRole('heading', { name: '重新认识一下自己' })).toBeVisible()
  await page.getByLabel('名字').fill('旅人澄')
  await page.getByRole('button', { name: '保存档案' }).click()
  await expect(page.getByRole('heading', { name: '旅人澄' })).toBeVisible()
  await page.locator('.nav-item').filter({ hasText: '设置' }).click()
  await expect(page.getByLabel('模型预设')).toHaveValue('zhipu-flash')
  await page.getByLabel('模型预设').selectOption('qwen-flash')
  await expect(page.getByLabel('模型 Endpoint')).toHaveValue('https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions')
  await expect(page.getByLabel('模型名称')).toHaveValue('qwen-flash')
  await page.getByLabel('模型预设').selectOption('zhipu-flash')
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.locator('.connection-result')).toContainText('请先在此页面填写 API Key')
  await expect(page.locator('.provider-save-status')).toContainText('已自动保存到本设备')
  await page.locator('.action-mode-option').filter({ hasText: '自由行动' }).click()
  await page.locator('.nav-item').filter({ hasText: '当前场景' }).click()
  await expect(page.getByRole('textbox', { name: '输入你的行动' })).toBeVisible()
  await expect(page.locator('#script-switcher option')).toHaveCount(1)
  await page.locator('.nav-item').filter({ hasText: '角色' }).click()
  await page.getByRole('button', { name: '重新开始人生' }).click()
  await expect(page.getByRole('heading', { name: '开始一段新人生' })).toBeVisible()
  await page.getByLabel('名字').fill('港口澄')
  await page.locator('.life-map-option').filter({ hasText: '灰潮港' }).click()
  await page.getByLabel('年龄阶段').selectOption('adult')
  await page.getByRole('button', { name: '开始这段人生' }).click()
  await expect(page.getByRole('main').getByRole('heading', { name: '灰潮港' })).toBeVisible()
  await expect(page.getByRole('main').getByText('港口澄', { exact: true })).toBeVisible()
  await expect(page.locator('#life-switcher option')).toHaveCount(2)
  expect(errors).toEqual([])
})

test('mobile keeps action-first layout and bottom navigation', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'mobile-only flow')
  await page.goto('/')
  await expect(page.locator('.bottom-nav')).toBeVisible()
  await expect(page.locator('.action-section')).toBeVisible()
  await expect(page.locator('.action-card').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('provider error details remain visible in settings', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'desktop-only provider proxy flow')
  await page.route('**/api/ai-proxy/zhipu', async (route) => {
    await route.fulfill({
      status: 401,
      contentType: 'application/json',
      body: JSON.stringify({ error: { code: 1214, message: '令牌已过期或验证不正确' } }),
    })
  })
  await page.goto('/')
  await page.locator('.nav-item').filter({ hasText: '设置' }).click()
  await page.getByLabel('模型 Endpoint').fill('http://127.0.0.1:4175/api/ai-proxy/zhipu')
  await page.getByLabel('模型 API Key').fill('invalid-test-key-only')
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.locator('.connection-result')).toContainText('服务器反馈：')
  await expect(page.locator('.connection-result')).toContainText(/令牌已过期或验证不正确|token expired or incorrect/)
  await expect(page.locator('.connection-result')).toContainText('HTTP 401')
  await expect(page.locator('.connection-result')).not.toContainText('API Key 未通过验证')
})

test('a baby life does not start with adult NPC relationships', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'desktop-only flow')
  await page.goto('/')
  await page.getByRole('button', { name: '开始一段新人生' }).click()
  await page.getByLabel('名字').fill('新生儿测试')
  await page.locator('.life-map-option').filter({ hasText: '灰潮港' }).click()
  await page.getByLabel('年龄阶段').selectOption('baby')
  await page.getByRole('button', { name: '开始这段人生' }).click()
  await page.locator('.nav-item').filter({ hasText: '人物' }).click()
  await expect(page.getByRole('heading', { name: '他们也在过自己的生活' })).toBeVisible()
  const cards = page.locator('.person-card')
  await expect(cards).toHaveCount(0)
  await expect(page.getByText('还没有认识这里的人')).toBeVisible()
})
